version: '3.8'

services:
  web:
    build: .
    container_name: arabgt_web
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - core/.env

  db:
    image: mysql:8.0
    container_name: arabgt_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: qbtbherhgs
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    env_file:
      - core/.env
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
