# Generated by Django 4.2.4 on 2024-07-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publish_date', models.DateTimeField()),
                ('edit_date', models.DateTimeField()),
                ('category', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
    ]
