# Generated by Django 4.2.4 on 2024-07-17 11:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_post_category_alter_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='related_articles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
