# Generated by Django 4.2.4 on 2024-07-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_savedpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='related_articles',
        ),
        migrations.AddField(
            model_name='post',
            name='related_articles',
            field=models.ManyToManyField(blank=True, to='api.post'),
        ),
    ]
