# Generated by Django 4.2.4 on 2024-08-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_forum_group_question_deleteduser_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='question'),
        ),
    ]
