# Generated by Django 4.2.4 on 2024-08-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_question_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('ios', 'Ios'), ('android', 'Android')])),
                ('release_type', models.CharField(choices=[('soft', 'Soft'), ('hard', 'Hard')])),
                ('version_number', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
