# Generated by Django 4.2.4 on 2024-08-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_mobilerelease'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(default='post', max_length=255),
            preserve_default=False,
        ),
    ]
