# Generated by Django 4.2.4 on 2024-08-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_post_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reply'),
        ),
    ]
