# Generated by Django 4.2.4 on 2024-08-15 08:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_reply_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleteduser',
            name='car_sorting',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('coupe_cars', 'سيارات كوبيه'), ('sports_cars', 'سيارات رياضية'), ('hyper_cars', 'سيارات هايبر كارز'), ('small_sedan', 'سيارات سيدان صغيرة'), ('medium_sedan', 'سيدان متوسط'), ('luxury_sedan', 'سيدان فخم'), ('crossover_cars', 'سيارات كروس اوفر'), ('SUVs', 'سيارات دفع رباعي'), ('large_SUVs', 'سيارات دفع رباعي كبيرة'), ('small_pickup _trucks', 'سيارات بيك اب صغير'), ('medium_sized_trucks', 'شاحنات متوسطة الحجم'), ('hatchback_cars', 'سيارات هاتش باك'), ('electric_cars', 'سيارات كهربائية'), ('hybrid_cars', 'سيارات هايبرد')], max_length=30), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='deleteduser',
            name='interests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('economics_and_business', 'الاقتصاد والأعمال'), ('automobiles', 'السيارات'), ('health_and_fitness', 'الصحة واللياقة البدنية'), ('technology', 'تكنولوجيا'), ('entertainment_and_music', 'الترفيه والموسيقى'), ('car_customization', 'تعديل سيارات'), ('cooking_and_recipes', 'الطبخ والوصفات'), ('driving_tips_and_techniques', 'نصائح وتقنيات القيادة'), ('fashion_and_style', 'الموضة والأناقة'), ('car_financing', 'تمويل السيارات'), ('future_mobility', 'مستقبل التنقل'), ('environment', 'البيئة'), ('luxury_cars', 'السيارات الفاخرة')], max_length=30), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='car_sorting',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('coupe_cars', 'سيارات كوبيه'), ('sports_cars', 'سيارات رياضية'), ('hyper_cars', 'سيارات هايبر كارز'), ('small_sedan', 'سيارات سيدان صغيرة'), ('medium_sedan', 'سيدان متوسط'), ('luxury_sedan', 'سيدان فخم'), ('crossover_cars', 'سيارات كروس اوفر'), ('SUVs', 'سيارات دفع رباعي'), ('large_SUVs', 'سيارات دفع رباعي كبيرة'), ('small_pickup _trucks', 'سيارات بيك اب صغير'), ('medium_sized_trucks', 'شاحنات متوسطة الحجم'), ('hatchback_cars', 'سيارات هاتش باك'), ('electric_cars', 'سيارات كهربائية'), ('hybrid_cars', 'سيارات هايبرد')], max_length=30), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('economics_and_business', 'الاقتصاد والأعمال'), ('automobiles', 'السيارات'), ('health_and_fitness', 'الصحة واللياقة البدنية'), ('technology', 'تكنولوجيا'), ('entertainment_and_music', 'الترفيه والموسيقى'), ('car_customization', 'تعديل سيارات'), ('cooking_and_recipes', 'الطبخ والوصفات'), ('driving_tips_and_techniques', 'نصائح وتقنيات القيادة'), ('fashion_and_style', 'الموضة والأناقة'), ('car_financing', 'تمويل السيارات'), ('future_mobility', 'مستقبل التنقل'), ('environment', 'البيئة'), ('luxury_cars', 'السيارات الفاخرة')], max_length=30), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='deleteduser',
            name='hobbies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('car_customization', 'تعديل السيارات وضبطها'), ('car_sports', 'رياضة السيارات'), ('test_drive', 'تجارب القيادة'), ('car_collection_restoration', 'مع وترميم السيارات'), ('diy_cars', 'مشاريع السيارات DIY'), ('photography', 'التصوير الفوتوغرافي'), ('video_games', 'الألعاب الإلكترونية'), ('trips_travel', 'الرحلات والسفر'), ('sport_hobies', 'هوايات الرياضة (كرة القدم، الجري، ركوب الدراجات)'), ('reading_writing', 'القراءة والكتابة')], max_length=30), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='hobbies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('car_customization', 'تعديل السيارات وضبطها'), ('car_sports', 'رياضة السيارات'), ('test_drive', 'تجارب القيادة'), ('car_collection_restoration', 'مع وترميم السيارات'), ('diy_cars', 'مشاريع السيارات DIY'), ('photography', 'التصوير الفوتوغرافي'), ('video_games', 'الألعاب الإلكترونية'), ('trips_travel', 'الرحلات والسفر'), ('sport_hobies', 'هوايات الرياضة (كرة القدم، الجري، ركوب الدراجات)'), ('reading_writing', 'القراءة والكتابة')], max_length=30), blank=True, default=list, size=None),
        ),
    ]
