# Generated by Django 4.2.4 on 2024-08-22 09:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleteduser',
            name='favorite_cars',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('dodge', 'دودج'), ('genesis', 'جينيسيس'), ('ram', 'رام'), ('bentley', 'بنتلي'), ('mitsubishi', 'ميتسوبيشي'), ('subaru', 'سوبارو'), ('lincoln', 'لينكولن'), ('lexus', 'لكزس'), ('hyundai', 'هيونداي'), ('haval', 'هافال'), ('suzuki', 'سوزوكي'), ('renault', 'رينو'), ('skoda', 'سكودا'), ('chrysler', 'كرايسلر'), ('peugeot', 'بيجو'), ('maybach', 'مايباخ'), ('porsche', 'بورش'), ('mg', 'ام جي'), ('rivian', 'ريفيان'), ('citroen', 'سيتروين'), ('maserati', 'مازيراتي'), ('geely', 'جيلي'), ('volvo', 'فولفو'), ('jaguar', 'جاكوار'), ('mazda', 'مازدا'), ('lucid', 'لوسيد'), ('ferrari', 'فيراري'), ('rolls royce', 'رولز رويس'), ('mercedes', 'مرسيدس'), ('lamborghini', 'لمبرجيني'), ('mini', 'ميني'), ('smart', 'سمارت'), ('gmc', 'جي ام سي'), ('fiat', 'فيات'), ('range rover', 'رنج روفر'), ('jeep', 'جيب'), ('honda', 'هوندا'), ('changan', 'شانجان'), ('nissan', 'نيسان'), ('mclaren', 'ماكلارين'), ('lotus', 'لوتس'), ('volkswagen', 'فولكس فاجن'), ('cadillac', 'كاديلاك'), ('kia', 'كيا'), ('chevrolet', 'شيفروليه'), ('land rover', 'لاند روفر'), ('tesla', 'تسلا')], max_length=30), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_cars',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('dodge', 'دودج'), ('genesis', 'جينيسيس'), ('ram', 'رام'), ('bentley', 'بنتلي'), ('mitsubishi', 'ميتسوبيشي'), ('subaru', 'سوبارو'), ('lincoln', 'لينكولن'), ('lexus', 'لكزس'), ('hyundai', 'هيونداي'), ('haval', 'هافال'), ('suzuki', 'سوزوكي'), ('renault', 'رينو'), ('skoda', 'سكودا'), ('chrysler', 'كرايسلر'), ('peugeot', 'بيجو'), ('maybach', 'مايباخ'), ('porsche', 'بورش'), ('mg', 'ام جي'), ('rivian', 'ريفيان'), ('citroen', 'سيتروين'), ('maserati', 'مازيراتي'), ('geely', 'جيلي'), ('volvo', 'فولفو'), ('jaguar', 'جاكوار'), ('mazda', 'مازدا'), ('lucid', 'لوسيد'), ('ferrari', 'فيراري'), ('rolls royce', 'رولز رويس'), ('mercedes', 'مرسيدس'), ('lamborghini', 'لمبرجيني'), ('mini', 'ميني'), ('smart', 'سمارت'), ('gmc', 'جي ام سي'), ('fiat', 'فيات'), ('range rover', 'رنج روفر'), ('jeep', 'جيب'), ('honda', 'هوندا'), ('changan', 'شانجان'), ('nissan', 'نيسان'), ('mclaren', 'ماكلارين'), ('lotus', 'لوتس'), ('volkswagen', 'فولكس فاجن'), ('cadillac', 'كاديلاك'), ('kia', 'كيا'), ('chevrolet', 'شيفروليه'), ('land rover', 'لاند روفر'), ('tesla', 'تسلا')], max_length=30), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='deleteduser',
            name='car_sorting',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('coupe_cars', 'سيارات كوبيه'), ('sports_cars', 'سيارات رياضية'), ('hyper_cars', 'سيارات هايبر كارز'), ('small_sedan', 'سيارات سيدان صغيرة'), ('medium_sedan', 'سيدان متوسط'), ('luxury_sedan', 'سيدان فخم'), ('crossover_cars', 'سيارات كروس اوفر'), ('SUVs', 'سيارات دفع رباعي'), ('large_SUVs', 'سيارات دفع رباعي كبيرة'), ('small_pickup_trucks', 'سيارات بيك اب صغير'), ('medium_sized_trucks', 'شاحنات متوسطة الحجم'), ('hatchback_cars', 'سيارات هاتش باك'), ('electric_cars', 'سيارات كهربائية'), ('hybrid_cars', 'سيارات هايبرد')], max_length=30), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='car_sorting',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('coupe_cars', 'سيارات كوبيه'), ('sports_cars', 'سيارات رياضية'), ('hyper_cars', 'سيارات هايبر كارز'), ('small_sedan', 'سيارات سيدان صغيرة'), ('medium_sedan', 'سيدان متوسط'), ('luxury_sedan', 'سيدان فخم'), ('crossover_cars', 'سيارات كروس اوفر'), ('SUVs', 'سيارات دفع رباعي'), ('large_SUVs', 'سيارات دفع رباعي كبيرة'), ('small_pickup_trucks', 'سيارات بيك اب صغير'), ('medium_sized_trucks', 'شاحنات متوسطة الحجم'), ('hatchback_cars', 'سيارات هاتش باك'), ('electric_cars', 'سيارات كهربائية'), ('hybrid_cars', 'سيارات هايبرد')], max_length=30), blank=True, default=list, size=None),
        ),
    ]
