# Generated by Django 4.2.4 on 2024-08-26 08:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_deleteduser_favorite_cars_user_favorite_cars_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='pinned_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
