# Generated by Django 4.2.4 on 2024-08-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_notification_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
