# Generated by Django 4.2.4 on 2024-08-27 09:12

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_question_pinned_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleteduser',
            name='favorite_cars',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('dodge', 'دودج'), ('genesis', 'جينيسيس'), ('ram', 'رام'), ('bentley', 'بنتلي'), ('mitsubishi', 'ميتسوبيشي'), ('subaru', 'سوبارو'), ('Lincoln', 'لينكولن'), ('Lexus', 'لكزس'), ('hyundai', 'هيونداي'), ('haval', 'هافال'), ('suzuki', 'سوزوكي'), ('renault', 'رينو'), ('skoda', 'سكودا'), ('chrysler', 'كرايسلر'), ('peugeot', 'بيجو'), ('maybach', 'مايباخ'), ('porsche', 'بورش'), ('mg', 'ام جي'), ('rivian', 'ريفيان'), ('citroen', 'سيتروين'), ('maserati', 'مازيراتي'), ('geely', 'جيلي'), ('volvo', 'فولفو'), ('jaguar', 'جاكوار'), ('mazda', 'مازدا'), ('lucid', 'لوسيد'), ('ferrari', 'فيراري'), ('rolls_royce', 'رولز رويس'), ('mercedes', 'مرسيدس'), ('lamborghini', 'لمبرجيني'), ('mini', 'ميني'), ('smart', 'سمارت'), ('gmc', 'جي ام سي'), ('fiat', 'فيات'), ('range_rover', 'رنج روفر'), ('jeep', 'جيب'), ('honda', 'هوندا'), ('changan', 'شانجان'), ('nissan', 'نيسان'), ('mclaren', 'ماكلارين'), ('lotus', 'لوتس'), ('volkswagen', 'فولكس فاجن'), ('cadillac', 'كاديلاك'), ('kia', 'كيا'), ('chevrolet', 'شيفروليه'), ('land_rover', 'لاند روفر'), ('tesla', 'تسلا')], max_length=30), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='pinned_by',
            field=models.ManyToManyField(blank=True, related_name='pinned_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite_cars',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('dodge', 'دودج'), ('genesis', 'جينيسيس'), ('ram', 'رام'), ('bentley', 'بنتلي'), ('mitsubishi', 'ميتسوبيشي'), ('subaru', 'سوبارو'), ('Lincoln', 'لينكولن'), ('Lexus', 'لكزس'), ('hyundai', 'هيونداي'), ('haval', 'هافال'), ('suzuki', 'سوزوكي'), ('renault', 'رينو'), ('skoda', 'سكودا'), ('chrysler', 'كرايسلر'), ('peugeot', 'بيجو'), ('maybach', 'مايباخ'), ('porsche', 'بورش'), ('mg', 'ام جي'), ('rivian', 'ريفيان'), ('citroen', 'سيتروين'), ('maserati', 'مازيراتي'), ('geely', 'جيلي'), ('volvo', 'فولفو'), ('jaguar', 'جاكوار'), ('mazda', 'مازدا'), ('lucid', 'لوسيد'), ('ferrari', 'فيراري'), ('rolls_royce', 'رولز رويس'), ('mercedes', 'مرسيدس'), ('lamborghini', 'لمبرجيني'), ('mini', 'ميني'), ('smart', 'سمارت'), ('gmc', 'جي ام سي'), ('fiat', 'فيات'), ('range_rover', 'رنج روفر'), ('jeep', 'جيب'), ('honda', 'هوندا'), ('changan', 'شانجان'), ('nissan', 'نيسان'), ('mclaren', 'ماكلارين'), ('lotus', 'لوتس'), ('volkswagen', 'فولكس فاجن'), ('cadillac', 'كاديلاك'), ('kia', 'كيا'), ('chevrolet', 'شيفروليه'), ('land_rover', 'لاند روفر'), ('tesla', 'تسلا')], max_length=30), blank=True, default=list, size=None),
        ),
    ]
