# Generated by Django 4.2.4 on 2024-08-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_deleteduser_favorite_cars_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
