# Generated by Django 4.2.4 on 2024-08-28 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_forum_description_group_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_saved', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('is_shared', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.post')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfilePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.BooleanField(default=False)),
                ('last_name', models.BooleanField(default=False)),
                ('nick_name', models.BooleanField(default=False)),
                ('birth_date', models.BooleanField(default=False)),
                ('nationality', models.BooleanField(default=False)),
                ('country', models.BooleanField(default=False)),
                ('gender', models.BooleanField(default=False)),
                ('phone_number', models.BooleanField(default=False)),
                ('favorite_presenter', models.BooleanField(default=False)),
                ('favorite_show', models.BooleanField(default=False)),
                ('hobbies', models.BooleanField(default=False)),
                ('interests', models.BooleanField(default=False)),
                ('favorite_cars', models.BooleanField(default=False)),
                ('car_sorting', models.BooleanField(default=False)),
                ('has_car', models.BooleanField(default=False)),
                ('car_type', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='point',
            field=models.IntegerField(default=5),
        ),
        migrations.DeleteModel(
            name='SavedPost',
        ),
        migrations.AddField(
            model_name='userprofilepoint',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='postaction',
            unique_together={('user', 'post')},
        ),
    ]
