# Generated by Django 4.2.4 on 2024-09-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_postaction_userprofilepoint_user_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='send_notification',
            field=models.BooleanField(default=True),
        ),
    ]
