# Generated by Django 4.2.4 on 2024-09-02 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_user_send_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='modify_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
