# Generated by Django 4.2.4 on 2024-09-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_post_modify_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
