# Generated by Django 4.2.4 on 2024-09-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_groupmembership_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritepresenter',
            name='image',
            field=models.ImageField(upload_to='favorite_presenter'),
        ),
        migrations.AlterField(
            model_name='favoriteshow',
            name='image',
            field=models.ImageField(upload_to='favorite_show'),
        ),
    ]
