# Generated by Django 4.2.4 on 2024-09-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_favoritepresenter_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleteduser',
            name='delete_reason',
            field=models.TextField(blank=True),
        ),
    ]
