# Generated by Django 4.2.4 on 2024-09-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_deleteduser_delete_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleteduser',
            name='point',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deleteduser',
            name='rank',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
