# Generated by Django 4.2.4 on 2024-09-27 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_delete_reaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
    ]
