# Generated by Django 4.2.4 on 2024-10-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_question_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='report_count',
            field=models.IntegerField(default=0),
        ),
    ]
