# Generated by Django 4.2.4 on 2024-10-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_question_report_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='file_extension',
            field=models.CharField(blank=True, max_length=20, null=True),
        )
    ]
