# Generated by Django 4.2.4 on 2024-10-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_question_file_extension_alter_deleteduser_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='file_extension',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
