# Generated by Django 4.2.4 on 2024-11-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_reply_file_extension_alter_deleteduser_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleteduser',
            name='user_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
