# Generated by Django 4.2.4 on 2024-11-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_deleteduser_user_id_alter_deleteduser_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='normalized_title',
            field=models.CharField(blank=True, max_length=255),
        )
    ]
