# Generated by Django 4.2.4 on 2024-11-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_post_normalized_title_alter_deleteduser_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
