# Generated by Django 4.2.4 on 2024-11-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_adminnotification_alter_deleteduser_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postaction',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postaction',
            name='saved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postaction',
            name='shared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
