# Generated by Django 4.2.4 on 2024-12-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_user_is_onboarded_alter_deleteduser_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_notification',
            field=models.BooleanField(default=False),
        ),
    ]
