# Generated by Django 4.2.4 on 2024-11-26 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0037_user_is_onboarded_alter_deleteduser_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='file',
        ),
        migrations.RemoveField(
            model_name='question',
            name='file_extension',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='file',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='file_extension',
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='files')),
                ('object_id', models.PositiveIntegerField()),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=5, blank=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
