# Generated by Django 4.2.4 on 2024-12-31 09:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_user_has_notification_alter_deleteduser_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='newsletter',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofilepoint',
            name='has_business',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofilepoint',
            name='newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
