# Generated by Django 4.2.4 on 2025-02-06 07:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_remove_question_file_remove_question_file_extension_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofilepoint',
            old_name='favorite_show',
            new_name='favorite_shows',
        ),
        migrations.RemoveField(
            model_name='deleteduser',
            name='favorite_show',
        ),
        migrations.RemoveField(
            model_name='user',
            name='favorite_show',
        ),
        migrations.AddField(
            model_name='deleteduser',
            name='favorite_shows',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_shows',
            field=models.ManyToManyField(blank=True, to='api.favoriteshow'),
        ),
    ]
