# Generated by Django 4.2.4 on 2025-01-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_remove_question_file_remove_question_file_extension_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='newsletter',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofilepoint',
            name='has_business',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofilepoint',
            name='newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
