# Generated by Django 4.2.4 on 2025-03-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_rename_favorite_show_userprofilepoint_favorite_shows_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotification',
            name='external_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='external_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
