# Generated by Django 4.2.4 on 2025-03-11 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_adminnotification_external_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='image',
        ),
    ]
