# Generated by Django 4.2.4 on 2025-08-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_post_is_published'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['newsletter'], name='api_user_newslet_cae06e_idx'),
        ),
    ]
